version: "3"

services:
  autolock: # サービスの名前
    container_name: autolock_main
    build:
      context: autolock_main # Dockerfileが存在するディレクトリを指定
      dockerfile: Dockerfile # 使用するDockerfileを指定
    image: autolock_main_img
    privileged: true # 特権モードを有効にする
    volumes:
      - autolock_setting_volume:/home/pi/autolock/gear_version/etc
    networks:
      - autolock_net

  mqtt_broker:
    container_name: autolock_mqtt_broker
    build:
      context: mqtt_broker
      dockerfile: Dockerfile
    image: autolock_mqtt_broker_img
    ports:
      - "1883:1883" #mqtt
    networks:
      - autolock_net

  auth_db:
    container_name: autolock_auth_db
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - auth_db_volume:/var/lib/mysql
      - ./auth_db:/docker-entrypoint-initdb.d
    networks:
      - autolock_net

  setting_webapp:
    container_name: autolock_setting_webapp
    build:
      context: setting_webapp
      dockerfile: Dockerfile
    image: autolock_webapp_img
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      BASE_URL: ${BASE_URL}
    ports:
      - "8080:3000"
    networks:
      - autolock_net

  webhook:
    container_name: autolock_webhook
    build:
      context: webhook
      dockerfile: Dockerfile
    image: autolock_webhook
    ports:
      - "3000:3000"
    networks:
      - autolock_net

networks:
  autolock_net:

volumes:
  auth_db_volume:
  autolock_setting_volume:
