#このファイルは手動で変更しない
version: "3" # Docker Composeのバージョン

services:
  ServiceName: # サービスの名前
    container_name: autolock
    build:
      context: . # Dockerfileが存在するディレクトリを指定
      dockerfile: Dockerfile # 使用するDockerfileを指定
    image: autolock_img
    privileged: true # 特権モードを有効にする
